### ISSUE TITLE
Random Reboot,Auto Rotation and Auto Brightness Issue

### ISSUE THREAD

**Issue by praveen7682** [MoKee/android_device_xiaomi_cancro#1]
Thanks for the official update..But still we have issues with auto rotate&Brightness, Random Reboot..there is a AOSPA rom build which seems to be more stable..Can we use the build from audahadi so that this ROM will have less issues...once again thanks for the updates...

**Comment by Ryuinferno** [comment]
We do not accept bug reports here, see http://issues.mokeedev.com
