### ISSUE TITLE
Compiled ROM won't boot

### ISSUE THREAD

**Issue by KaiJan57** [MoKee/android_device_xiaomi_cancro#6]
Hi! I built LineageOS using this device tree (mkp). However, I end up in a bootloop after flashing it. I think the main error message is as follows:
`
F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F DEBUG   : LineageOS Version: '16.0-20190520-UNOFFICIAL-cancro'
F DEBUG   : Build fingerprint: 'Xiaomi/cancro/cancro:6.0.1/MMB29M/V8.1.6.0.MXDMIDI:user/release-keys'
F DEBUG   : Revision: '0'
F DEBUG   : ABI: 'arm'
F DEBUG   : pid: 9600, tid: 9754, name: system-server-i  >>> system_server <<<
F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
F DEBUG   : Abort message: 'Sensors.cpp:98] Check failed: getHalDeviceVersion() >= ((((1) & 0xff) << 24) | (((3) & 0xff) << 16) | ((1) & 0xffff)) (getHalDeviceVersion()=16777217, ((((1) & 0xff) << 24) | (((3) & 0xff) << 16) | ((1) & 0xffff))=16973825) '
F DEBUG   :     r0  00000000  r1  0000261a  r2  00000006  r3  00000008
F DEBUG   :     r4  00002580  r5  0000261a  r6  92478e54  r7  0000010c
F DEBUG   :     r8  00000002  r9  ac71c8e0  r10 921cb23d  r11 ac5a242e
F DEBUG   :     ip  00000041  sp  92478e40  lr  af4b5125  pc  af4ace4a

`
Does anyone know how to fix this?

**Comment by DrRamm** [comment]
@KaiJan57 provide full log

**Comment by KaiJan57** [comment]
Okay I got that log, truncated to repeat only once:
[logcat.txt](https://github.com/MoKee/android_device_xiaomi_cancro/files/3203216/logcat.txt)

Following "mods" used: Magisk, RiruCore, EdXposed, microG (FakeGapps), F-droid

**Comment by DrRamm** [comment]
> Following "mods" used

are u high? Don't use any mods


fix that 
`05-21 16:40:39.926   309   309 F linker  : CANNOT LINK EXECUTABLE "log": library "libshim_atomic.so" not found`

**Comment by KaiJan57** [comment]
Do you think mods are the cause of _these_ problems?
I think there is something wrong with msm8974-common: The QCamera HAL is still on 1.0:
`msm8974-common/camera/QCamera2/HAL/QCamera2HWI.cpp:1109:    mCameraDevice.common.version = HARDWARE_DEVICE_API_VERSION(1, 0);`

Do you have an idea on how to fix that atomic library thing?

**Comment by KaiJan57** [comment]
Okay, I'll take a look at a boot without Magisk involved...

**Comment by KaiJan57** [comment]
Nope. Same issue! See logcat. This time not truncated :-P
[logcat.txt](https://github.com/MoKee/android_device_xiaomi_cancro/files/3203559/logcat.txt)

**Comment by KaiJan57** [comment]
*bump

**Comment by DrRamm** [comment]
@KaiJan57 `F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/netmgrd": cannot locate symbol "ds_system_call3" referenced by "/system/vendor/bin/netmgrd"...`

**Comment by DrRamm** [comment]
```
05-21 18:26:23.249   402   402 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/netmgrd": cannot locate symbol "ds_system_call3" referenced by "/system/vendor/bin/netmgrd"...
05-21 18:26:23.250   364   364 D libEGL  : loaded /vendor/lib/egl/libEGL_adreno.so
05-21 18:26:23.250   364   364 D vndksupport: Loading /vendor/lib/egl/libGLESv1_CM_adreno.so from current namespace instead of sphal namespace.
05-21 18:26:23.256   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/listener_android.c:109:listener using ion heap: -1
05-21 18:26:23.258   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: ./oemconfig.so No such file or directory
05-21 18:26:23.259   364   364 D libEGL  : loaded /vendor/lib/egl/libGLESv1_CM_adreno.so
05-21 18:26:23.276   364   364 D vndksupport: Loading /vendor/lib/egl/libGLESv2_adreno.so from current namespace instead of sphal namespace.
05-21 18:26:23.279   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: /vendor/lib/rfsa/adsp/./oemconfig.so No such file or directory
05-21 18:26:23.279   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: /system/vendor/lib/rfsa/adsp/./oemconfig.so No such file or directory
05-21 18:26:23.279   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/../inc/mod_table_imp.h:346::error: 2: 0 == (nErr = invoke_func_ptr(sc, pra))
05-21 18:26:23.279   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: ./voiceproc_tx.so No such file or directory
05-21 18:26:23.279   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: /vendor/lib/rfsa/adsp/./voiceproc_tx.so No such file or directory
05-21 18:26:23.279   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: /system/vendor/lib/rfsa/adsp/./voiceproc_tx.so No such file or directory
05-21 18:26:23.279   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/../inc/mod_table_imp.h:346::error: 2: 0 == (nErr = invoke_func_ptr(sc, pra))
05-21 18:26:23.280   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: ./voiceproc_rx.so No such file or directory
05-21 18:26:23.280   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: /vendor/lib/rfsa/adsp/./voiceproc_rx.so No such file or directory
05-21 18:26:23.280   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/apps_std_imp.c:33:apps_std fopen failed: /system/vendor/lib/rfsa/adsp/./voiceproc_rx.so No such file or directory
05-21 18:26:23.280   406   411 E adsprpc : vendor/qcom/proprietary/adsprpc/src/../inc/mod_table_imp.h:346::error: 2: 0 == (nErr = invoke_func_ptr(sc, pra))
```

**Comment by KaiJan57** [comment]
Okay. Now I reset the whole repositories. Turns out that there are still CANNOT LINK EXECUTABLE errors. Do you know what kernel is to be used? I compiled this thing with this one: https://github.com/LineageOS/android_kernel_xiaomi_cancro, branch: cm-14.1
For this one: https://github.com/MoKee/android_kernel_xiaomi_cancro I don't really know what branch to use...

**Comment by DrRamm** [comment]
@KaiJan57 a u high? 

> I built LineageOS using this device tree (mkp)

>  branch: cm-14.1

mkp - pie 
cm-14.1 - nougat

**Comment by KaiJan57** [comment]
So what kernel tree to use?

**Comment by KaiJan57** [comment]
MoKee does not provide a "mkp" branched kernel for cancro, so...

**Comment by DrRamm** [comment]
https://github.com/Ratoriku/kernel_xiaomi_virgo-cancro/commits/mkp

**Comment by KaiJan57** [comment]
So I remove android_kernel_xiaomi_cancro and the rom should just boot fine?
By the way: I had that virgo kernel included in the past few builds

**Comment by KaiJan57** [comment]
I recompiled and still the same errors with CANNOT LINK EXECUTABLE.

**Comment by DrRamm** [comment]
> I recompiled 

well u asked about right kernel and I've answered. 
CANNOT LINK EXECUTABLE its not kernel related problem u should know

**Comment by KaiJan57** [comment]
Yeah but it still is a problem related to this device tree, isn't it?

**Comment by KaiJan57** [comment]
This is the logcat I get:
[logcat.txt](https://github.com/MoKee/android_device_xiaomi_cancro/files/3224589/logcat.txt)

**Comment by D3nesyan** [comment]
@KaiJan57 just use virgo kernel

**Comment by KaiJan57** [comment]
Yes of course I built the last ROM with the virgo kernel after @DrRamm recommended it!
Still, I am getting these weird errors, which I don't know how to solve.

**Comment by KaiJan57** [comment]
Guess what? I ran make clean and rebuilt everything without changing my setup, resulting in a very well bootable ROM. Thank you very much for your support and helpful tips!
I ended up using the following repos:
- this one
- https://github.com/MoKee/android_kernel_xiaomi_virgo/tree/mkp
- https://github.com/MoKee/android_device_xiaomi_msm8974-common/tree/mkp
- https://github.com/MoKee/android_vendor_xiaomi_msm8974-common/tree/mkp
- https://github.com/MoKee/android_vendor_xiaomi_cancro/tree/mkp
- https://github.com/LineageOS/android
Additionally, I have changed the MoKee branded naming to the LineageOS branded one.
